name: Notify Discord on PR Assignment

on:
  pull_request:
    types: [assigned]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Notify Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        ASSIGNEES: ${{ toJson(github.event.pull_request.assignees) }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: |
        ASSIGNEES_MENTION=$(echo "$ASSIGNEES" | jq -r 'map("@" + .login) | join(", ")')
        EMBED_MESSAGE=$(jq -n \
          --arg title "$PR_TITLE" \
          --arg url "$PR_URL" \
          --arg assignees "Assigned to: $ASSIGNEES_MENTION" \
          '{embeds: [{title: $title, url: $url, description: $assignees, color: 5814783}]}')
        curl -H "Content-Type: application/json" \
          -d "$EMBED_MESSAGE" \
          $DISCORD_WEBHOOK_URL
